############################################################
# YAML file to build container images
# AUTHOR: Axel Quack <mail@axelquack.de>
# Version 0.1
############################################################

jenkins:
  service:
    image: guttertec/jenkins
    name: jenkins
    port: "8080"
  images:
    - ubuntu
    - jdk6-oracle
    - jenkins

redis:
  service:
    image: guttertec/redis
    name: redis
    port: "6379"
  images:
    - ubuntu
    - redis

mongo:
  service:
    image: guttertec/mongodb
    name: mongodb
    port: "27017"
  images:
    - ubuntu
    - mongodb

rails:
  service:
    image: guttertec/rails-sample-app
    name: rails-sample-app
    port: "3000"
  images:
    - ubuntu
    - ruby
    - ruby-rails
    - rails-sample-app

ghost:
  service:
    image: guttertec/ghost
    name: ghost
    port: "2368"
  images:
    - ubuntu
    - nodejs
    - ghost

minecraft:
  service:
    image: guttertec/minecraft
    name: minecraft
    port: "25565"
  images:
    - ubuntu
    - openjdk7
    - minecraft

couchpotato
  service:
    image: guttertec/couchpotato
    name: couchpotato
    port: "5050"
  images:
    - ubuntu
    - couchpotato

sabnzbd
  service:
    image: guttertec/sabnzbd
    name: sabnzbd
    port: "8080"
  images:
    - ubuntu
    - sabnbzd

sickbeard
  service:
    image: guttertec/sickbeard
    name: sickbeard
    port: "8081"
  images:
    - ubuntu
    - sickbeard

znc
  service:
    image: guttertec/znc
    name: znc
    port: "6667"
  images:
    - ubuntu
    - znc

hubot-irc
  service:
    image: guttertec/hubot-irc
    name: hubot-irc
    port: "9980"
  images:
    - ubuntu
    - nodejs
    - hubot
    - hubot-irc